import {canResearchQuestion,researchForJob,markResearchDraftUsed} from './google-research.js';
import {canDraftProfessional,draftForJob} from './answer-drafts.js';
import {researchConsentWithdrawn} from './research-consent.js';
const parse=s=>{try{return JSON.parse(s||'{}')}catch{return {}}};
export async function prepareFormAnswer(db,uid,id,question,{research=researchForJob,draft=draftForJob,check=()=>'',expectedOwner=null,choices=[],answerFormat='text',maxLength=4000,fieldHelp=''}={}){
 if(typeof question!=='string'||question.length<3||question.length>4000)throw Error('A complete employer question is required.');
 if(!Array.isArray(choices)||choices.length>80||choices.some(v=>typeof v!=='string'||!v.trim()||v.length>200)||new Set(choices.map(v=>v.trim().toLowerCase())).size!==choices.length)throw Error('This dropdown needs review because its options are ambiguous or unsupported.');
 const choiceAnswer=value=>{if(typeof value!=='string'||!value.trim())return '';if(!choices.length)return value;const found=choices.filter(c=>c.trim().toLowerCase()===value.trim().toLowerCase());return found.length===1?found[0]:'';};
 const read=()=>db.prepare('SELECT * FROM jobs WHERE id=? AND user_id=?').get(id,uid);
 const profile=j=>j&&db.prepare('SELECT * FROM applicants WHERE id=? AND user_id=?').get(j.applicant_id,uid);
 const eligible=(j,p)=>j&&p?.consent&&j.status==='local_browser'&&!j.local_attempt_at&&!j.handoff_available&&(!expectedOwner||j.local_owner===expectedOwner)&&!db.prepare("SELECT 1 FROM events WHERE job_id=? AND type IN ('submission_started','manual_submission','submitted')").get(id);
 let job=read(),p=profile(job);
 if(!eligible(job,p))throw Error('This form cannot be prepared now. Check its current application status.');
 const problem=check(job);if(problem)throw Error(problem);
 if(researchConsentWithdrawn(db,id,p.id))throw Error('AI answer consent changed. Review this application.');
 const publicQuestion=canResearchQuestion(question),personal=!publicQuestion&&canDraftProfessional(question);
 if(choices.length&&(publicQuestion||!canDraftProfessional(question+' '+fieldHelp)))return {answer:'',reason:'This dropdown needs your saved answer or review.'};
 if(publicQuestion?!p.google_research_consent:!personal||!p.gemini_facts_consent&&!p.ai_consent)return {answer:'',reason:'This question needs your saved answer or review.'};
 const existing=parse(job.answers_json)[question];
 if(choiceAnswer(existing))return existing.length>maxLength?{answer:'',reason:'Your saved answer is longer than this employer field allows. Shorten it for this application.'}:{answer:choiceAnswer(existing),source:'saved',requiresReview:true};
 const owner=job.local_owner,applicant=job.applicant_id,url=job.url;
 const result=publicQuestion?await research(db,uid,id,question):await draft(db,uid,id,question,{choices,answerFormat,maxLength,fieldHelp});
 job=read();p=profile(job);
 if(!eligible(job,p)||job.local_owner!==owner||job.applicant_id!==applicant||job.url!==url||check(job)||researchConsentWithdrawn(db,id,p.id)||(publicQuestion?!p.google_research_consent:result.provider==='gemini'?!p.gemini_facts_consent:!p.ai_consent))throw Error('The form or your consent changed while drafting. Your answers were preserved.');
 const answers=parse(job.answers_json);
 if(typeof answers[question]==='string'&&answers[question].trim()&&(!choices.length||answers[question]!==existing))return {answer:choiceAnswer(answers[question]),source:'saved',requiresReview:true,reason:'Your saved answer was preserved. Review it if it does not match these options.'};
 if(!result.answer?.trim())return result;
 if(choices.length&&!choiceAnswer(result.answer))return {answer:'',reason:'Gemini did not return one of the current dropdown options.'};
 if(choices.length&&existing?.trim())return {...result,answer:choiceAnswer(result.answer),source:'approved_facts',requiresReview:true};
 Object.defineProperty(answers,question,{value:result.answer.trim(),enumerable:true,configurable:true,writable:true});
 db.prepare('UPDATE jobs SET answers_json=?,updated_at=? WHERE id=?').run(JSON.stringify(answers),new Date().toISOString(),id);
 if(publicQuestion)markResearchDraftUsed(db,id,question);
 return {...result,source:publicQuestion?'public_page':'approved_facts',requiresReview:true};
}
