import {chromium} from 'playwright';import {createHash} from 'node:crypto';import {db,event,now} from './db.js';
import {runDueSearches} from './discovery.js';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function hostAllowed(url){let u=new URL(url);return u.protocol==='https:'&&/(^|\.)(greenhouse\.io|lever\.co|myworkdayjobs\.com|workdayjobs\.com)$/.test(u.hostname)}
function set(job,status,message,challenge=null,confirmation=null){db.prepare('UPDATE jobs SET status=?,challenge=?,confirmation=?,updated_at=? WHERE id=?').run(status,challenge,confirmation,now(),job.id);event(job.id,status,message)}
function claim(){db.exec('BEGIN IMMEDIATE');try{let j=db.prepare("SELECT * FROM jobs WHERE status='queued' ORDER BY created_at LIMIT 1").get();if(j){db.prepare("UPDATE jobs SET status='running',attempts=attempts+1,lease_at=?,updated_at=? WHERE id=?").run(now(),now(),j.id);event(j.id,'running','Opening employer application')}db.exec('COMMIT');return j}catch(e){db.exec('ROLLBACK');throw e}}
async function field(page,labels){for(let label of labels){let l=page.getByLabel(label,{exact:false});if(await l.count()===1&&await l.isVisible())return l}for(let s of labels){let l=page.locator(`input[name*="${s}" i], input[placeholder*="${s}" i], textarea[name*="${s}" i]`);if(await l.count()===1&&await l.isVisible())return l}return null}
async function fill(page,p){let n=0;for(let [labels,value] of [[['First name','first_name','firstName'],p.name.split(/\s+/)[0]],[['Last name','last_name','lastName'],p.name.split(/\s+/).slice(1).join(' ')],[['Full name','Your name'],p.name],[['Email','email'],p.email],[['Phone','phone'],p.phone],[['Location','City'],p.location]]){if(!value)continue;let l=await field(page,labels);if(!l)continue;let type=await l.getAttribute('type');if(['file','radio','checkbox','hidden'].includes(type))continue;if(await l.inputValue().catch(()=>'')!=='')continue;await l.fill(value);n++}return n}
async function review(page){return page.evaluate(()=>{let captcha=!!document.querySelector('iframe[src*="captcha"],.g-recaptcha,[class*="captcha"],[id*="captcha"]');let signIn=!!document.querySelector('input[type="password"]');let missing=[...document.querySelectorAll('input:required,textarea:required,select:required,[aria-required="true"]')].filter(e=>{if(!e.getClientRects().length)return false;if(e.type==='file')return !e.files?.length;if(e.type==='radio')return ![...document.querySelectorAll('input[type="radio"]')].some(other=>other.name===e.name&&other.form===e.form&&other.checked);if(e.type==='checkbox')return !e.checked;return !e.value}).map(e=>e.labels?.[0]?.innerText?.trim()||e.getAttribute('aria-label')||e.name||'Required field');return {captcha,signIn,missing:[...new Set(missing)]}})}
async function aiAnswer(q,p,j){if(!p.ai_consent||!process.env.OPENAI_API_KEY||!process.env.OPENAI_MODEL)return null;let facts=JSON.parse(p.answers_json||'{}');let key=createHash('sha256').update(JSON.stringify({applicant:p.id,q,facts,role:j.title,company:j.company,model:process.env.OPENAI_MODEL})).digest('hex');let cached=db.prepare('SELECT answer FROM answer_cache WHERE cache_key=?').get(key);if(cached)return cached.answer;let response=await fetch('https://api.openai.com/v1/responses',{method:'POST',signal:AbortSignal.timeout(30000),headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL,store:false,input:[{role:'system',content:'Answer briefly using only the supplied applicant facts. If facts are insufficient, reply exactly NEEDS_HUMAN. Never invent credentials, work authorization, experience, availability or salary.'},{role:'user',content:JSON.stringify({question:q,role:j.title,facts})}],max_output_tokens:180})});if(!response.ok)throw Error(`AI service returned ${response.status}`);let d=await response.json(),answer=(d.output_text||d.output?.flatMap(x=>x.content||[]).map(x=>x.text||'').join('')||'').trim();if(answer&&answer!=='NEEDS_HUMAN'){let value=answer.slice(0,1000);db.prepare('INSERT OR IGNORE INTO answer_cache VALUES(?,?,?)').run(key,value,now());return value}return null}
async function custom(page,p,j){let answers=JSON.parse(p.answers_json||'{}'),inputs=page.locator('textarea:visible,input[type="text"]:visible,input:not([type]):visible'),n=await inputs.count(),unresolved=[];for(let i=0;i<Math.min(n,50);i++){let l=inputs.nth(i);if(await l.inputValue().catch(()=>'')!=='')continue;let q=await l.evaluate(e=>(e.labels?.[0]?.innerText||e.getAttribute('aria-label')||e.placeholder||'').trim().replace(/\s+/g,' ').slice(0,240));if(!q)continue;let match=Object.keys(answers).find(k=>k.trim().replace(/\s*\*$/,'').toLowerCase()===q.replace(/\s*\*$/,'').toLowerCase()),a=match?answers[match]:null;if(!a&&/why|describe|tell us|cover letter|interest|experience/i.test(q))a=await aiAnswer(q,p,j);if(a){await l.fill(String(a));event(j.id,'answer',`Answered: ${q}`)}else unresolved.push(q)}return unresolved}
async function selections(page,p){
 const answers=JSON.parse(p.answers_json||'{}');
 const normalize=s=>String(s).trim().replace(/\s+/g,' ').replace(/\s*\*$/,'').toLowerCase();
 const selects=page.locator('select:visible');
 for(let i=0;i<await selects.count();i++){
  const el=selects.nth(i),q=await el.evaluate(e=>e.labels?.[0]?.innerText||e.getAttribute('aria-label')||'');
  const key=Object.keys(answers).find(k=>normalize(k)===normalize(q));if(!key)continue;
  const options=await el.locator('option').evaluateAll(xs=>xs.map(x=>({label:x.textContent,value:x.value,disabled:x.disabled})));
  const choices=options.filter(x=>!x.disabled&&(normalize(x.label)===normalize(answers[key])||x.value===String(answers[key])));
  if(choices.length===1)await el.selectOption(choices[0].value);
 }
}
async function run(job,browser){let p=db.prepare('SELECT * FROM applicants WHERE id=? AND user_id=?').get(job.applicant_id,job.user_id);if(p)p={...p,answers_json:JSON.stringify({...JSON.parse(p.answers_json||'{}'),...JSON.parse(job.answers_json||'{}')})};if(!p?.consent||!p.email||!p.resume_path)return set(job,'needs_review','Profile needs consent, email and resume');if(!hostAllowed(job.url))return set(job,'needs_review','Supported hosts: Greenhouse, Lever and Workday');let context=await browser.newContext({acceptDownloads:false,locale:'en-CA'});let page=await context.newPage();try{await page.goto(job.url,{waitUntil:'domcontentloaded',timeout:45000});await page.waitForTimeout(1200);if(!hostAllowed(page.url()))return set(job,'needs_review','Employer redirected to a website that needs review');let check=await review(page);if(check.captcha)return set(job,'paused','Human verification required','CAPTCHA');if(check.signIn)return set(job,'paused','Sign-in required','Sign-in');let apply=page.getByRole('button',{name:/^(apply|apply now|apply for this job)$/i});let applyLink=page.getByRole('link',{name:/^apply for this job$/i});if(await apply.count()===1){await apply.click();await page.waitForTimeout(800);if(!hostAllowed(page.url()))return set(job,'needs_review','Application redirected to an unsupported site')}else if(await applyLink.count()){let urls=await applyLink.evaluateAll(links=>[...new Set(links.map(link=>link.href))]);if(urls.length!==1||!hostAllowed(urls[0]))return set(job,'needs_review','Application link needs review');await applyLink.first().click();await page.waitForTimeout(800);if(!hostAllowed(page.url()))return set(job,'needs_review','Application redirected to an unsupported site')}
let filled=await fill(page,p);event(job.id,'filled',`Filled ${filled} standard fields`);let file=page.locator('input[type="file"]'),count=await file.count();if(count===1)await file.setInputFiles(p.resume_path);else if(count>1){const resume=page.getByLabel(/resume|résumé|cv/i);if(await resume.count()===1&&await resume.getAttribute('type')==='file')await resume.setInputFiles(p.resume_path);else return set(job,'needs_review','Several upload fields need review');}else return set(job,'needs_review','Resume upload field was not found');await selections(page,p);let unknown=await custom(page,p,job);check=await review(page);if(check.captcha)return set(job,'paused','Human verification required','CAPTCHA');if(check.signIn)return set(job,'paused','Sign-in required','Sign-in');if(check.missing.length)return set(job,'needs_review',`Missing required fields: ${check.missing.slice(0,8).join('; ')}`,'Missing answers');let unanswered=await page.locator('input[type=radio]:visible').evaluateAll(radios=>[...new Set(radios.filter(r=>!document.querySelector(`input[type=radio][name=\"${CSS.escape(r.name)}\"]:checked`)).map(r=>r.name||'Radio question'))]);if(unanswered.length)return set(job,'needs_review',`Unanswered selection questions: ${unanswered.slice(0,8).join('; ')}`,'Missing answers');if(!filled)return set(job,'needs_review','Application form was not recognized');let submit=page.getByRole('button',{name:/^(submit application|submit|send application)$/i});if(await submit.count()!==1)return set(job,'needs_review',`Submit button not recognized${unknown.length?`; questions: ${unknown.slice(0,4).join('; ')}`:''}`);const current=db.prepare('SELECT consent FROM applicants WHERE id=?').get(p.id);if(!current?.consent)return set(job,'needs_review','Consent was withdrawn');set(job,'running','About to submit; automatic retry disabled','Submission in progress');await submit.click();await page.waitForTimeout(2000);let content=(await page.locator('body').innerText()).slice(0,10000);if(/thank you for (applying|your application)|application (has been )?(submitted|received)|successfully applied/i.test(content))return set(job,'submitted','Employer confirmed receipt',null,'Confirmation page');set(job,'needs_review','Submit clicked but receipt was not confirmed. Check employer site before retrying.','Unconfirmed submission')
}catch(e){set(job,'needs_review',`Worker stopped: ${String(e.message).slice(0,350)}`,db.prepare('SELECT challenge FROM jobs WHERE id=?').get(job.id)?.challenge==='Submission in progress'?'Unconfirmed submission':'Worker error')}finally{await context.close()}}
async function main(){db.prepare("UPDATE jobs SET status='needs_review',challenge=CASE WHEN challenge='Submission in progress' THEN 'Unconfirmed submission' ELSE 'Worker interrupted' END,updated_at=? WHERE status='running'").run(now());let browser=await chromium.launch({headless:true});console.log('ApplyPilot worker running');const heartbeat=()=>db.prepare('INSERT INTO worker_status VALUES(1,?) ON CONFLICT(id) DO UPDATE SET heartbeat=excluded.heartbeat').run(now());heartbeat();setInterval(heartbeat,10000);let discoveryBusy=false;async function discoveryTick(){if(discoveryBusy)return;discoveryBusy=true;try{await runDueSearches()}catch(e){console.error('Discovery:',e)}finally{discoveryBusy=false}}setInterval(discoveryTick,60000);discoveryTick();process.on('SIGTERM',async()=>{await browser.close();process.exit(0)});for(;;){let j=claim();if(j)await run(j,browser);else await sleep(3000)}}main().catch(e=>{console.error(e);process.exit(1)});
