const {JSDOM}=require('jsdom');const fs=require('fs');const assert=require('node:assert/strict');
const root=require('path').join(__dirname,'../');
const dom=new JSDOM(fs.readFileSync(root+'assistant-page.html','utf8'),{url:'https://applypilot-jobs.netlify.app/automate.html',runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window,requests=[];w.setInterval=()=>0;w.setTimeout=()=>0;w.clearTimeout=()=>{};
let release;w.fetch=async(url,opts)=>{requests.push({url,data:opts.body&&JSON.parse(opts.body)});if(url.endsWith('/view'))await new Promise(r=>release=r);return {ok:true,json:async()=>url.includes('/handoff/')?{image:'AA==',frameId:'frame',host:'jobs.lever.co',expiresAt:Date.now()+600000}:{jobs:[],workerOnline:true}};};
const tick=()=>new Promise(r=>setImmediate(r));
(async()=>{w.eval(fs.readFileSync(root+'assistant-client.js','utf8'));const opening=w.eval('openHandoff({id:"fixture",title:"Cloud Engineer"})');await tick();const surface=w.document.querySelector('#live-surface');assert(surface);assert.equal(w.document.activeElement,surface);
for(const key of ['h','i','Tab','ArrowLeft'])surface.dispatchEvent(new w.KeyboardEvent('keydown',{key,bubbles:true,cancelable:true}));assert.equal(requests.length,1,'input waits in order during the in-flight view');release();await opening;for(let i=0;i<8;i++)await tick();
const actions=requests.filter(r=>!r.url.endsWith('/view'));assert.deepEqual(actions.map(r=>r.data),[{text:'hi',render:false},{key:'Tab',render:false},{key:'ArrowLeft',render:false}]);assert(actions.every(r=>r.url.includes('/handoff/')));assert(w.document.body.textContent.includes('Continue automatically'));assert(w.document.body.textContent.includes('Close view'));dom.window.close();console.log('PASS: direct keyboard entry is ordered, coalesced and sent without screenshot waits');})().catch(e=>{console.error(e);dom.window.close();process.exitCode=1});
