const {JSDOM}=require('jsdom'),fs=require('fs'),assert=require('node:assert/strict'),path=require('path');
const root=path.join(__dirname,'../'),dom=new JSDOM(fs.readFileSync(root+'assistant-page.html','utf8'),{url:'https://applypilot-jobs.netlify.app/automate.html',runScripts:'outside-only'}),w=dom.window;
w.setInterval=()=>0;const requests=[];let jobs=[],failSave=false,failContinue=false;
w.fetch=async(url,options)=>{requests.push({url,options});const payload=options.body?JSON.parse(options.body):{},j=jobs.find(j=>url.includes('/jobs/'+j.id+'/'));
if(url.endsWith('/answers')){if(failSave)return{ok:false,json:async()=>({error:'Save unavailable'})};const answers=JSON.parse(j.answers_json||'{}');answers[payload.question]=payload.answer;j.answers_json=JSON.stringify(answers);}
if(url.endsWith('/continue')){if(failContinue)return{ok:false,json:async()=>({error:'Worker unavailable'})};j.status='queued';}
return{ok:true,json:async()=>url.endsWith('/applicants')?{applicants:[{id:'p',answers:{'Country of Residence':'Canada'}}]}:url.endsWith('/jobs')?{jobs}: {workerOnline:true}}};
const job=(id,applicant_id='p',challenge='Missing answers')=>({id,applicant_id,challenge,status:'needs_review',company:'Example',title:'Support',required_fields_json:'["Country of Residence","Passport Country"]'});
const section=()=>w.document.querySelector('#missing-answers'),fields=()=>[...section().querySelectorAll('textarea')],submit=()=>section().querySelector('form').onsubmit({preventDefault(){}}),render=()=>{w.fixtureJobs=jobs;w.eval('renderMissingAnswers(fixtureJobs)')};
(async()=>{w.eval(fs.readFileSync(root+'assistant-client.js','utf8'));jobs=[job('a'),job('b'),job('c','other'),job('captcha','p','CAPTCHA')];render();assert.equal(fields().length,4,'groups stay scoped to profile');await [...section().querySelectorAll('button')].find(b=>b.textContent==='Fill from saved profile').onclick();assert.equal(fields()[0].value,'Canada');assert.equal(fields()[1].value,'','passport must not be inferred');assert.equal(fields()[2].value,'','other profile stays blank');await submit();assert.equal(requests.filter(r=>r.options.method==='PUT').length,2);assert.equal(requests.filter(r=>r.url.endsWith('/continue')).length,0,'partial answers must not queue');assert.equal(fields().length,3,'saved question disappears');assert.equal(fields()[0].getAttribute('aria-label'),'Passport Country');
fields()[0].value='User supplied test answer';failSave=true;await submit();assert.equal(fields()[0].value,'User supplied test answer','failed input retained');failSave=false;failContinue=true;await submit();assert.equal(fields().length,2,'successful saves disappear even when queue fails');assert.equal(jobs[0].status,'needs_review');failContinue=false;await submit();assert.equal(jobs[0].status,'queued','retry uses durable previously saved answers');assert.equal(jobs[1].status,'queued');
fields().forEach(f=>f.value='Other profile test answer');await submit();assert.equal(section().hidden,true,'form disappears when no questions remain');assert.equal(jobs[3].status,'needs_review','verification remains untouched');assert(requests.filter(r=>r.url.endsWith('/continue')).every(r=>!r.url.includes('captcha')));
jobs.push({...job('new'),required_fields_json:'["New employer question"]'});render();assert.equal(section().hidden,false,'new questions bring the form back');assert.equal(fields().length,1);assert.equal(fields()[0].value,'');console.log('PASS: partial saves advance, failures retain text, complete answers resume, empty form hides, new questions return, verification untouched');w.close()})().catch(e=>{console.error(e);w.close();process.exitCode=1});
