const {JSDOM}=require('jsdom'),fs=require('fs'),assert=require('node:assert/strict'),path=require('path');
const root=path.join(__dirname,'../'),target=process.argv[2],pages={'assistant-client.js':'assistant-page.html','web/progress.js':'web/progress.html'},page=pages[target];
assert(page,'usage: node checks/missing-answers.cjs <assistant-client.js|web/progress.js>');
const dom=new JSDOM(fs.readFileSync(path.join(root,page),'utf8'),{url:'https://applypilot-jobs.netlify.app/automate.html',runScripts:'outside-only'}),w=dom.window;
w.setInterval=()=>0;const requests=[];let jobs=[],failSave=false,failContinue=false;
w.fetch=async(url,options)=>{requests.push({url,options});const payload=options.body?JSON.parse(options.body):{},j=jobs.find(j=>url.includes('/jobs/'+j.id+'/'));
if(url.endsWith('/answers')){if(failSave)return{ok:false,json:async()=>({error:'Save unavailable'})};const answers=JSON.parse(j.answers_json||'{}');answers[payload.question]=payload.answer;j.answers_json=JSON.stringify(answers);}
if(url.endsWith('/continue')){if(failContinue)return{ok:false,json:async()=>({error:'Worker unavailable'})};j.status='queued';}
const path=new URL(String(url)).pathname;const response=path.endsWith('/applicants')?{applicants:[{id:'p',answers:{'Country of Residence':'Canada'},reusableAnswers:{'Country of Residence':'Canada'}}]}:path.endsWith('/jobs')?{jobs}:path.endsWith('/status')?{workerOnline:true}:path.endsWith('/application-history')?{records:[]}:path.endsWith('/operations')?{applications:[],totals:{}}:path.endsWith('/activity')?{events:[]}:path.endsWith('/continuations')?{requests:[]}:path.endsWith('/pipeline')?{enabled:false,eligible:0,queued:0}:path.endsWith('/employer-limits')?{limits:[]}:path.endsWith('/notifications')?{enabled:false,configured:false}:path.endsWith('/searches')?{searches:[],intervalSeconds:60}:path.endsWith('/ai-status')?{profiles:[],attempts:[]}:path.endsWith('/work-focus')?{enabled:false,parked:0}:{workerOnline:true};return{ok:true,json:async()=>response}};
const job=(id,applicant_id='p',challenge='Missing answers')=>({id,applicant_id,challenge,status:'needs_review',company:'Example',title:'Support',required_fields_json:'["Country of Residence","Passport Country"]'});
const section=()=>w.document.querySelector('#missing-answers'),fields=()=>[...section().querySelectorAll('textarea')],submit=()=>section().querySelector('form').onsubmit({preventDefault(){}}),render=()=>{w.fixtureJobs=jobs;w.eval('renderMissingAnswers(fixtureJobs)')};
(async()=>{w.eval(fs.readFileSync(root+'extension/policy.js','utf8'));w.eval(fs.readFileSync(path.join(root,target),'utf8'));jobs=[job('a'),job('b'),job('c','other'),job('captcha','p','CAPTCHA')];render();assert.equal(fields().length,4,'groups stay scoped to profile');let copied='';Object.defineProperty(w.navigator,'clipboard',{configurable:true,value:{writeText:async text=>{copied=text;}}});const copy=[...section().querySelectorAll('button')].find(b=>b.textContent==='Copy question for ChatGPT');assert.equal(copy.type,'button');const beforeCopy=requests.length;await copy.onclick();assert.equal(copied,'Country of Residence');assert.equal(requests.length,beforeCopy,'copy makes no network or save request');assert.equal(fields()[0].value,'','copy does not fabricate an answer');const open=section().querySelector('a[href="https://chatgpt.com/"]');assert(open&&open.rel.includes('noreferrer'));w.navigator.clipboard.writeText=async()=>{throw Error('Denied')};await copy.onclick();const fallback=section().querySelector('[aria-label="Question to copy manually"]');assert(fallback.readOnly);assert.equal(fallback.value,'Country of Residence');assert.equal(requests.length,beforeCopy);w.navigator.clipboard.writeText=async text=>{copied=text};await copy.onclick();assert.equal(section().querySelector('[aria-label="Question to copy manually"]'),null);await [...section().querySelectorAll('button')].find(b=>b.textContent==='Fill from saved profile').onclick();assert.equal(fields()[0].value,'Canada');assert.equal(fields()[1].value,'','passport must not be inferred');assert.equal(fields()[2].value,'','other profile stays blank');await submit();assert.equal(requests.filter(r=>r.options.method==='PUT').length,2);assert.equal(requests.filter(r=>r.url.endsWith('/continue')).length,0,'partial answers must not queue');assert.equal(fields().length,3,'saved question disappears');assert.equal(fields()[0].getAttribute('aria-label'),'Passport Country');
fields()[0].value='User supplied test answer';failSave=true;await submit();assert.equal(fields()[0].value,'User supplied test answer','failed input retained');failSave=false;failContinue=true;await submit();assert.equal(fields().length,2,'successful saves disappear even when queue fails');assert.equal(jobs[0].status,'needs_review');failContinue=false;await submit();assert.equal(jobs[0].status,'queued','retry uses durable previously saved answers');assert.equal(jobs[1].status,'queued');
fields().forEach(f=>f.value='Other profile test answer');await submit();assert.equal(section().querySelector('form'),null,'form disappears when no questions remain');if(target==='assistant-client.js')assert(section().textContent.includes('No unanswered questions right now.'));assert.equal(jobs[3].status,'needs_review','verification remains untouched');assert(requests.filter(r=>r.url.endsWith('/continue')).every(r=>!r.url.includes('captcha')));
jobs.push({...job('new'),required_fields_json:'["New employer question"]'});render();assert.equal(section().hidden,false,'new questions bring the form back');assert.equal(fields().length,1);assert.equal(fields()[0].value,'');console.log(`PASS [${target}]: partial saves advance, failures retain text, complete answers resume, empty form hides, new questions return, verification untouched`);w.close()})().catch(e=>{console.error(e);w.close();process.exitCode=1});
