
// Persist only an explicitly remembered session, never the password.
function restoreSession(){const remembered=localStorage.getItem('applypilot-remembered-token');if(remembered)sessionStorage.setItem('applypilot-token',remembered);return remembered||sessionStorage.getItem('applypilot-token')||'';}
function saveSession(value,remember){sessionStorage.setItem('applypilot-token',value);if(remember)localStorage.setItem('applypilot-remembered-token',value);else localStorage.removeItem('applypilot-remembered-token');}
function clearSession(){sessionStorage.removeItem('applypilot-token');localStorage.removeItem('applypilot-remembered-token');localStorage.setItem('applypilot-signout',String(Date.now()));}
window.addEventListener('storage',e=>{if(e.key==='applypilot-signout'){sessionStorage.removeItem('applypilot-token');location.reload();}});
function rememberOption(form){const label=document.createElement('label'),box=document.createElement('input');box.type='checkbox';box.name='remember';box.style.cssText='width:auto;display:inline;margin-right:8px';label.style.cssText='display:block;margin:12px 0';label.append(box,document.createTextNode('Keep me signed in on this computer for up to 30 days'));form.insertBefore(label,form.querySelector('button'));return box;}
const API=(location.hostname.endsWith('.netlify.app')||location.hostname.endsWith('.pages.dev'))?'https://marvelous-vitality-production-c2d8.up.railway.app/api':'/api';
const $=s=>document.querySelector(s);let token=restoreSession(),profiles=[];
async function api(path,method='GET',data){const r=await fetch(API+path,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d;}
const notice=message=>$('#message').textContent=message;
async function load(){profiles=(await api('/applicants')).applicants;const select=$('#profiles'),chosen=select.value;select.replaceChildren(new Option('Create a new profile',''));for(const p of profiles)select.add(new Option(p.name,p.id));select.value=chosen;}
const rememberLogin=rememberOption($('#account'));
$('#account').onsubmit=async e=>{e.preventDefault();try{token=(await api('/'+e.submitter.value,'POST',{...Object.fromEntries(new FormData(e.target)),remember:rememberLogin.checked})).token;saveSession(token,rememberLogin.checked);await load();notice('Signed in. Choose or create your applicant profile.');}catch(err){notice(err.message);}};
$('#profiles').onchange=()=>{const p=profiles.find(p=>p.id===$('#profiles').value),f=$('#profile');f.reset();if(p){for(const k of ['name','email','phone','location','focus','execution_mode'])f.elements[k].value=p[k]||'';f.elements.consent.checked=!!p.consent;}};
$('#profile').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{const f=e.target,existing=profiles.find(p=>p.id===$('#profiles').value),data={...Object.fromEntries(new FormData(f)),consent:f.elements.consent.checked,answers:existing?.answers||{},ai_consent:!!existing?.ai_consent};let id=existing?.id;if(id)await api('/applicants/'+id,'PUT',data);else id=(await api('/applicants','POST',data)).id;const file=$('#resume').files[0];let warning='';if(file){const r=await fetch(API+'/applicants/'+id+'/resume',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':file.name.toLowerCase().endsWith('.pdf')?'application/pdf':'application/vnd.openxmlformats-officedocument.wordprocessingml.document'},body:file});const d=await r.json();if(!r.ok)throw Error(d.error);warning=d.resumeNotice||'';}await load();$('#profiles').value=id;notice('Profile saved. '+warning);}catch(err){notice(err.message);}finally{button.disabled=false;}};
for(const name of ['job','search'])$('#'+name).onsubmit=async e=>{e.preventDefault();try{const id=$('#profiles').value;if(!id)throw Error('Save or select an applicant profile first.');const data={...Object.fromEntries(new FormData(e.target)),applicant_id:id};if(name==='search'){data.auto_queue=e.target.elements.auto_queue.checked;const r=await api('/searches','POST',data);await api('/searches/'+r.id+'/run','POST',{});}else await api('/jobs','POST',data);notice(name==='job'?'Job added to Found. Open Applications and choose Apply automatically.':'Search completed. Review found jobs in the dashboard.');}catch(err){notice(err.message);}};
if(token)load().catch(err=>notice(err.message));

if((location.hostname.endsWith('.netlify.app')||location.hostname.endsWith('.pages.dev')))document.querySelector('#open-dashboard').href='/automate.html';
